---
title: "Sea-urchin-Upwelling-HW2"
output: html_document
---

##Introduction##

Title: 
Authors: 
Victoria French
Madison Pacaro 
Jamie Poirier 




##Version Control## 

R 4.0.2 
DESeq2 1.28.1
affycoretools 1.60.1
arrayQualityMetrics 3.46.0
genefilter 1.70.0
Biobase 2.48.0

```{r}

getRversion()

#DESeq
packageVersion("DESeq2")
packageVersion("affycoretools")
packageVersion("arrayQualityMetrics")
packageVersion("genefilter")
packageVersion("Biobase")

#GO 

#WGCNA

```


##Data Analysis##

```{r}
#Loadpackages 

#DESeq 
library(DESeq2) 
library(affycoretools)
library(arrayQualityMetrics)
library(genefilter)
library(Biobase)

#GO

#WGCNA

```

```{r}
#Setwd
#setwd("/usr4/bi594/vfrench3/assignment2/seaurchinupwelling")

```

```{r}
#create countdata variable 
countData <- read.table(file= "geneCounts_02122019.txt")
names(countData)=c("NN1", "NN2", "NN3", "UU1", "UU2", "UU3")
row.names(countData)=sub("", "isogroup", rownames(countData))
head(countData)
length(countData[,1])
```

```{r}
#Outliers

treat=c("NN1", "NN2", "NN3", "UU1", "UU2", "UU3")

#Creating coldata; data frame associating sample with treatment
g=data.frame(treat)
g
colData=g

#Calling on DESeq2 to create a model; storing results of analysis of differential expression; asking how our design varies by treatment 
dds=DESeqDataSetFromMatrix(countData=countData,
                           colData = g,
                           design = ~treat)

#Normalizing Data 
vsd.ge=assay(vst(dds))
rl=vst(dds)


#Identifying outliers in data
e=ExpressionSet(assay(rl), AnnotatedDataFrame(as.data.frame(colData(rl))))
arrayQualityMetrics(e,outdir=v,intgroup=c("treat"),force=T)
```

```{r}
#Total Counts 

totalCounts
#NN1 #NN2 #NN3 #UU1 #UU2 #UU3 
#8555156 #8577700 #8948115 #8570174 #7455015 #6376636
barplot(totalCounts, col=c("coral", "coral", "coral", "red", "red", "red"), ylab="raw counts")
#raw counts generally uniformly distributed! Good signal for normalization 

min(totalCounts) #our number is 6376636
max(totalCounts)  # our number is 8948115
```

```{r}
#Creating DESeq Object 
dds<-DESeqDataSetFromMatrix(countData=countData, colData=colData, design= ~ treat)

#one step DESeq
dds<-DESeq(dds)
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




